### ISSUE TITLE
Animations don't play when Hodgepodge's `speedupAnimations` is enabled

### ISSUE THREAD

**Issue by Tree-er233** [makamys/Neodymium#44]
Possible incompatibility issue with hodgepodge.
The animation of flowing fluids and some blocks doesn't play correctly, when Neodymium 0.2 exists. However, Neodymium 0.1.8.5 does not have this problem.
I have tested on GTNH 2.5.1 (both java8 and java21) and the issue does not appear when hodgepodge is disabled.
The video of my issue :

https://github.com/makamys/Neodymium/assets/110247896/82f2e0ec-9fd7-4551-96f9-cdb650715fba

https://github.com/makamys/Neodymium/assets/110247896/ff0d35b3-183f-451d-b151-eae7cc0ed63e

**Comment by makamys** [comment]
Looks like it's a regression in 0.2, I can reproduce it with that version but not with 0.1.9. Hodgepodge [hooks `WorldRenderer#getGLCallListForPass`](https://github.com/GTNewHorizons/Hodgepodge/blob/b2607e68e9b71c7a18ab880c9e362a02b383786c/src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/textures/client/MixinWorldRenderer.java#L39-L46) to decide which textures need to be updated, but the GL list logic was disabled in https://github.com/makamys/Neodymium/pull/43, so that's probably why.

You can disable Hodgepodge's `speedupAnimations` as a workaround until it's fixed.
