### ISSUE TITLE
[1.7.10] If I allocate a lot of vram, I have less fps and the chunks take a bit longer before they can load

### ISSUE THREAD

**Issue by quentin452** [makamys/Neodymium#8]
Mods list : 

Neodymium

Video : 
2048 mb vram alocated fps max 2500
https://mega.nz/file/eh0kkTJB#pZMLgHGqRa8qBiexfCZBr3ctkkNBzyxA_DuicG4BsDE

11000 mb vram alocated fps max 2300
https://mega.nz/file/G0lWUDKR#lFmSJW0btruMu0R6dwnyPXEdVvAMRnL78SD6O_xPZpI

**Comment by makamys** [comment]
That's only an 8% change in FPS. If this is based on only two experiments, it's not significant enough to prove that there is a real difference. Also, max FPS is not a good metric due to how much FPS fluctuates. Average FPS would be better.

As for chunk load speed, I can't see a significant difference there either. It takes 6.137 seconds for chunks to load in your video with 2048 MB VRAM, and 6.867 seconds in the video with 11000 MB. (I measured the difference between when you click the "Generate World" button, and when the last chunk appears.) That's only a 12% difference between two experiments. But I don't consider this a valid benchmark either in the first place, since what you're really measuring is world generation speed, which is a complex process the speed of which could be influenced by many factors.

I'm going to close this since I don't consider these results significant or reliable enough.
